---
title: "VDS2526"
author:
  - "Sofiya Antonyuk (2467715)"
  - "Benedict Pierret TAA NGUIMBIS ESSEME (2261512)"
  - "Viktor Szabó (2503521)"
  - "Ferenc Wimmer (2469928)"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)

# bring in your plots
source("SA_2a_4.R")

source("FW_1_3a_3b.R")
FWdata <- load_pollution_data("VDS2526_Madrid") # path to the folder that contains all the csv files (stations.csv can be present in the folder)
```

# Q1. Evolution of pollution in Madrid over time

```{r}
plot_yearly_averages(FWdata$df, FWdata$pollutants)
```

# Q2a. 2018 Average NO2 Hotspot Map

```{r}
SA_q2a_hotspot
```

# Q2a. 2018 Average NO2 Bar Chart

```{r}
SA_q2a_barchart
```

# 3a. Evolution of different pollutants

```{r}
plot_relative_change(FWdata$df, FWdata$pollutants)
```

# 3b. Correlation between pollutants

```{r}
plot_correlation_heatmap(FWdata$df, FWdata$pollutants)
```

# Q4. 2001-2018 Heat Map

```{r}
SA_q4_heatmap
```

